### ISSUE TITLE
add CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by Sriansh-raj** [Sriansh-raj/GitHub-Achievements#2]
Hey there!
idk about what should be written in `CODE_OF_CONDUCT`
can you please add the `CODE_OF_CONDUCT.md` file for this repo.

~ 😸

**Comment by IshaanAdarsh** [comment]
IshaanAdarsh:patch-1
- You can check this out (I added a basic Code of Conduct )

**Comment by Sriansh-raj** [comment]
> IshaanAdarsh:patch-1
> 
> * You can check this out (I added a basic Code of Conduct )

Thank you 😄 

You PR has been merged 👍🏻
