### ISSUE TITLE
No more Q&A In the discussion section

### ISSUE THREAD

**Issue by the-1Riddle** [Sriansh-raj/GitHub-Achievements#88]
problem:

there are no more Q&A in the discussion section for the  galaxy :brain: badges

How to solve the problem:

more more discussions should be created for that.

thnaks.

**Comment by Sriansh-raj** [comment]
HI @the-1Riddle 
I am sorry for that but due to academics and shortage of time, I am unable to maintain the thread, I started. 😞

**Comment by Sriansh-raj** [comment]
As I can see you already have a `galaxy Brain` tag right ? But if you want I can add some questions just for you, tell me how much do you want for now :)

**Comment by the-1Riddle** [comment]
> As I can see you already have a `galaxy Brain` tag right ? But if you want I can add some questions just for you, tell me how much do you want for now :)

```c
if(you have time)
{
    (then you can create eight of them for me to reach x2);
}
else
{
    (its still ok if you would be engaged as i already have the badge);
}
return (thanks);
```

**Comment by Sriansh-raj** [comment]
@the-1Riddle  as you said, 8 questions have been created. All are the easy ones :D

Go get your `X2` 🎉

**Comment by the-1Riddle** [comment]
> @the-1Riddle as you said, 8 questions have been created. All are the easy ones :D
> 
> Go get your `X2` 🎉

thanks let me check them out

**Comment by Sriansh-raj** [comment]
Don't forget to create a PR and update your name in [Users_who_got_Galaxy_Brain.md](https://github.com/Sriansh-raj/GitHub-Achievements/blob/main/Users_who_got_Galaxy_Brain.md) to create a history 😃
